-- Include the other files in /lua/tdj
require("tdj.set")
require("tdj.packer")
require("tdj.telescope")
require("tdj.cmp")
require("tdj.lsp")
require("tdj.autopairs")
require("tdj.comment")
require("tdj.gitsigns")
require("tdj.nvim-tree")
require("tdj.bufferline")
require("tdj.indent")
require("tdj.dap")
