vim.opt.completeopt = "menuone,noselect"
vim.opt.breakindent = false
vim.opt.nu = true
vim.opt.relativenumber = true
vim.opt.tabstop = 4
vim.opt.softtabstop = 4
vim.opt.shiftwidth = 4
vim.opt.expandtab = true
vim.opt.smartindent = false
vim.opt.hlsearch = false
vim.opt.incsearch = true
vim.opt.ignorecase = true
vim.opt.smartcase = true
vim.opt.cursorline = true
vim.opt.wrap = false
vim.opt.termguicolors = true
vim.g.mapleader = " "
vim.g.maplocalleader = " "
vim.opt.clipboard = "unnamedplus"
vim.opt.updatetime = 50
vim.opt.timeoutlen = 300
vim.opt.cmdheight = 1
vim.opt.swapfile = false
vim.opt.backup = false
vim.opt.undodir = os.getenv("HOME") .. "/.vim/undodir"
vim.opt.undofile = true
vim.opt.fileencoding = "utf-8"
vim.opt.showmode = false
vim.opt.signcolumn = "yes:1"
vim.opt.scrolloff = 8
vim.opt.sidescrolloff = 8
vim.opt.smartcase = true
vim.opt.guicursor = ""
vim.opt.errorbells = false
vim.wo.signcolumn = "yes"
